-- клиенты
CREATE TABLE public.customer (
    id integer generated by DEFAULT AS identity PRIMARY KEY,
    created_at timestamp NOT NULL DEFAULT NOW(),
    first_name varchar(64) NOT NULL,
    last_name varchar(64) NOT NULL,
    phone varchar(16) NOT NULL,
    email varchar(128)
);

-- визиты клиентов на сайте
CREATE TABLE public.customer_visit (
    id integer generated by DEFAULT AS identity PRIMARY KEY,
    customer_id integer REFERENCES customer(id),
    created_at timestamp NOT NULL DEFAULT NOW(), -- начало визита
    visit_length integer, -- продолжительность визита (в секундах)
    landing_page varchar(512) NOT NULL, -- адрес страницы входа
    exit_page varchar(512), -- адрес страницы выхода
    geo_tag circle, -- Примерное географическое местоположение пользователя
    utm_source varchar(128), -- источник визита (название рекламного канала)
    utm_data jsonb -- Доп данные визита
);

-- Расширения для использования индексов 
CREATE EXTENSION pg_trgm;
CREATE EXTENSION btree_gist;
